## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
 
def build(bld):
    env = bld.env_of_name('default')
    if not env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('error-model-test', ['core', 'mobility', 'wifi', 'applications', 'config-store', 'tools', 'visualizer'])
    obj.source = 'error-model-test.cc'



